Missing encoded byte connection in fd1089\!

diff --git a/ver/game/go b/ver/game/go
--- a/ver/game/go
+++ b/ver/game/go
@@ -14,6 +14,14 @@ source $AUXTMP
 
 while [ $# -gt 0 ]; do
     case $1 in
+        -g)
+            shift
+            GAME=$1
+            if [ ! -e $ROM/$GAME.rom ]; then
+                echo "Cannot find ROM file $ROM/$GAME.rom"
+                exit 1
+            fi
+            ;;
     	-s)
             shift
     		SCENE=$1;;
@@ -22,6 +30,8 @@ while [ $# -gt 0 ]; do
     esac
     shift
 done
+
+ln -sf $ROM/$GAME.rom rom.bin
 
 if [ ! -z "$SCENE" ]; then
 	echo "Simulating scene $SCENE"
